version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build: ./docker/php/
    expose:
      - 9000
    networks:
      - backend
    volumes:
      - .:/var/www/html
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/intl.ini:/usr/local/etc/php/conf.d/intl.ini
      - ./docker/php/redis.ini:/usr/local/etc/php/conf.d/redis.ini
      - ./docker/php/sendmail.ini:/usr/local/etc/php/conf.d/sendmail.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - ./docker/mariadb/settings.cnf:/etc/mysql/conf.d/settings.cnf
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - ./docker/data/redis:/data

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend: